import NextAuthProvider from '@/providers/NextAuth'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ height: '100vh' }}>
      <body className={inter.className} style={{ overflow: 'auto', height: '100%' }}>
        <main style={{ marginTop: '8%', overflow: 'hidden', height: '90%'}} >
        <NextAuthProvider>
          {children}
        </NextAuthProvider>
        </main>
      </body>
    </html>
  )
}
